import type { Tour } from "./tour-types";
import {
  privatePricing,
  STANDARD_INCLUDED,
  STANDARD_NOT_INCLUDED,
} from "./tour-pricing";
import tourPlitvice from "@/assets/tour-plitvice.jpg";
import tourNationalParks from "@/assets/tour-national-parks.jpg";
import tourDubrovnik from "@/assets/tour-dubrovnik.jpg";
import tourSlovenia from "@/assets/tour-slovenia.jpg";
import tourIstria from "@/assets/tour-istria-v2.jpg";
import tourWine from "@/assets/tour-wine.jpg";
import tourZagreb from "@/assets/tour-zagreb.jpg";
import tourZagrebCityBreak from "@/assets/tour-zagreb-city-break.jpg";
import tourBosnia from "@/assets/tour-bosnia.jpg";
import tourBudapestDubrovnik from "@/assets/tour-budapest-dubrovnik.jpg";
import tourViennaDubrovnik from "@/assets/tour-vienna-dubrovnik.jpg";
import tourCroatiaBosnia from "@/assets/tour-croatia-bosnia.jpg";
import tourGrandBalkans from "@/assets/tour-grand-balkans.jpg";
import tourPostojna from "@/assets/tour-postojna-v2.jpg";
import heroCoast from "@/assets/hero-coast.jpg";
import aboutVillage from "@/assets/about-village.jpg";

const NOTE =
  "Departure date on request. The itinerary can be customised according to your preferences.";

const BASE = {
  category: "multiday" as const,
  tourType: "Private",
  group: "Private tour · 2–6 guests",
  departure: "On request",
  fitness: 1,
  technical: 1,
  currency: "€",
  itineraryNote: NOTE,
  badge: "Multi-Day",
};

export const multidayTours: Tour[] = [
  {
    ...BASE,
    slug: "unesco-croatia-tour",
    title: "UNESCO Croatia Tour",
    shortTitle: "UNESCO Croatia",
    duration: "5 days",
    durationDays: "5 days",
    priceFrom: 590,
    image: tourPlitvice,
    intro:
      "Five days through Croatia's UNESCO World Heritage sites — Plitvice, Šibenik, Split, Trogir and Dubrovnik — with a private guide and boutique hotels.",
    description:
      "The essential cultural journey south from Zagreb, hitting every UNESCO-listed gem on the way to the Adriatic.",
    overview: [
      "Croatia has more UNESCO World Heritage sites per capita than almost any country in Europe — and this tour connects the finest of them in five perfectly paced days.",
      "From Plitvice Lakes to the medieval cores of Trogir and Dubrovnik, every stop is a masterpiece of nature or human heritage.",
      "Private vehicle, licensed guide and hand-picked 4★ hotels throughout.",
    ],
    destinations: ["Plitvice", "Šibenik", "Split", "Trogir", "Dubrovnik"],
    highlights: [
      "Plitvice Lakes National Park",
      "Šibenik Cathedral of St. James",
      "Diocletian's Palace in Split",
      "Trogir medieval old town",
      "Dubrovnik city walls",
    ],
    itinerary: [
      { time: "Day 1", title: "Zagreb → Plitvice", text: "National park visit and overnight near the lakes." },
      { time: "Day 2", title: "Plitvice → Šibenik → Split", text: "UNESCO cathedral and transfer to Split." },
      { time: "Day 3", title: "Split & Trogir", text: "Palace tour and afternoon in Trogir." },
      { time: "Day 4", title: "Split → Dubrovnik", text: "Scenic coastal drive with Ston stop." },
      { time: "Day 5", title: "Dubrovnik", text: "Old town walking tour and city walls." },
    ],
    included: [...STANDARD_INCLUDED, "4 nights in boutique 4★ hotels", "Daily breakfast", "All entrance fees listed"],
    notIncluded: [...STANDARD_NOT_INCLUDED, "Lunches and dinners", "Flights"],
    pricing: privatePricing(820, 700, 590),
  },
  {
    ...BASE,
    slug: "croatia-national-parks-tour",
    title: "Croatia National Parks Tour",
    shortTitle: "National Parks",
    duration: "5 days",
    durationDays: "5 days",
    priceFrom: 560,
    image: tourNationalParks,
    intro:
      "Plitvice Lakes, Paklenica, Krka and Mljet — Croatia's greatest national parks in one private five-day adventure.",
    description:
      "For nature lovers who want forests, waterfalls, islands and karst canyons without rushing.",
    overview: [
      "Croatia's eight national parks are among the most diverse in Europe — from continental lakes to Adriatic islands.",
      "This private tour links the four most spectacular: Plitvice, Paklenica, Krka and Mljet.",
      "Ideal for active travellers who want hiking, boat rides and unforgettable landscapes.",
    ],
    destinations: ["Plitvice", "Paklenica", "Krka", "Mljet"],
    highlights: [
      "Plitvice Lakes boardwalks and waterfalls",
      "Paklenica canyon hiking",
      "Krka National Park waterfalls",
      "Mljet island lakes by boat",
      "Private guide throughout",
    ],
    itinerary: [
      { time: "Day 1", title: "Zagreb → Plitvice", text: "Full day in Plitvice Lakes National Park." },
      { time: "Day 2", title: "Plitvice → Paklenica", text: "Canyon walk in Velebit mountains." },
      { time: "Day 3", title: "Paklenica → Krka", text: "Krka waterfalls and Šibenik." },
      { time: "Day 4", title: "Krka → Mljet", text: "Ferry to Mljet island national park." },
      { time: "Day 5", title: "Mljet → Dubrovnik", text: "Island morning, transfer to Dubrovnik." },
    ],
    included: [...STANDARD_INCLUDED, "4 nights accommodation", "Park entrance fees", "Ferry tickets"],
    notIncluded: ["Meals", "Optional activities", "Flights"],
    pricing: privatePricing(780, 665, 560),
  },
  {
    ...BASE,
    slug: "best-of-croatia-tour",
    title: "Best of Croatia Tour",
    shortTitle: "Best of Croatia",
    duration: "6 days",
    durationDays: "6 days",
    priceFrom: 650,
    image: heroCoast,
    intro:
      "The classic Croatia route — Zagreb, Plitvice, Zadar, Šibenik, Split and Dubrovnik — in six unforgettable private days.",
    description:
      "Our most popular multi-day itinerary: everything first-time visitors should see, nothing they shouldn't.",
    overview: [
      "Six days from the capital to the Pearl of the Adriatic, covering Croatia's highlights at a comfortable pace.",
      "Private vehicle, the same driver-guide throughout, and boutique hotels in every stop.",
      "Perfect for couples, families and small groups who want the full Croatian experience.",
    ],
    destinations: ["Zagreb", "Plitvice", "Zadar", "Šibenik", "Split", "Dubrovnik"],
    highlights: [
      "Plitvice Lakes National Park",
      "Zadar Sea Organ at sunset",
      "Šibenik UNESCO cathedral",
      "Diocletian's Palace, Split",
      "Dubrovnik old town and walls",
    ],
    itinerary: [
      { time: "Day 1", title: "Zagreb → Plitvice", text: "Lakes tour and overnight in Lika." },
      { time: "Day 2", title: "Plitvice → Zadar", text: "Coastal drive and Zadar old town." },
      { time: "Day 3", title: "Zadar → Šibenik → Split", text: "Cathedral visit and Split arrival." },
      { time: "Day 4", title: "Split", text: "Palace tour and free time on the Riva." },
      { time: "Day 5", title: "Split → Dubrovnik", text: "Scenic coast road via Ston." },
      { time: "Day 6", title: "Dubrovnik", text: "Full day in the walled city." },
    ],
    included: [...STANDARD_INCLUDED, "5 nights in 4★ hotels", "Daily breakfast", "Local guides in Split & Dubrovnik"],
    notIncluded: ["Park entrance fees", "Meals", "Flights"],
    pricing: privatePricing(890, 760, 650),
  },
  {
    ...BASE,
    slug: "best-of-croatia-slovenia-tour",
    title: "Best of Croatia and Slovenia Tour",
    shortTitle: "Croatia & Slovenia",
    duration: "8 days",
    durationDays: "8 days",
    priceFrom: 760,
    image: tourSlovenia,
    intro:
      "Eight days across two countries — Lake Bled, Ljubljana, Plitvice, Istria and the Adriatic — one private journey from Zagreb.",
    description:
      "The perfect combination for travellers who want both Alpine Slovenia and coastal Croatia in a single trip.",
    overview: [
      "Start in Slovenia's Julian Alps at Lake Bled, explore Ljubljana, then cross into Croatia for Plitvice, Istria and the Adriatic coast.",
      "One private vehicle and guide from start to finish — no switching drivers or coaches.",
      "Eight days of fairytale lakes, medieval towns and seaside sunsets.",
    ],
    destinations: ["Bled", "Ljubljana", "Plitvice", "Istria", "Opatija", "Zagreb"],
    highlights: [
      "Lake Bled and Bled Castle",
      "Ljubljana Old Town",
      "Plitvice Lakes National Park",
      "Motovun and Istrian hill towns",
      "Opatija Riviera",
    ],
    itinerary: [
      { time: "Day 1", title: "Zagreb → Bled", text: "Lake Bled and castle visit." },
      { time: "Day 2", title: "Bled → Ljubljana", text: "Capital city walking tour." },
      { time: "Day 3", title: "Ljubljana → Plitvice", text: "Cross into Croatia, lakes visit." },
      { time: "Day 4", title: "Plitvice", text: "Full day in the national park." },
      { time: "Day 5", title: "Plitvice → Istria", text: "Motovun and Hum." },
      { time: "Day 6", title: "Istria → Opatija", text: "Coastal drive to Opatija." },
      { time: "Day 7", title: "Opatija → Zagreb", text: "Return via scenic route." },
      { time: "Day 8", title: "Zagreb", text: "City tour and departure." },
    ],
    included: [...STANDARD_INCLUDED, "7 nights accommodation", "Daily breakfast", "Castle & park tickets"],
    notIncluded: ["Meals", "Wine tastings", "Flights"],
    pricing: privatePricing(1050, 890, 760),
  },
  {
    ...BASE,
    slug: "zagreb-dubrovnik-tour",
    title: "Zagreb Dubrovnik Tour",
    shortTitle: "Zagreb → Dubrovnik",
    duration: "6–7 days",
    durationDays: "6–7 days",
    priceFrom: 710,
    image: tourDubrovnik,
    intro:
      "The classic southbound journey — Plitvice, Krka, the Dalmatian coast and walled Dubrovnik — with boutique hotels and a private guide throughout.",
    description:
      "Everything arranged: accommodation, transfers, restaurant tips and local guides. Just show up and explore.",
    overview: [
      "Six to seven days from Zagreb to Dubrovnik, covering Plitvice Lakes, Krka National Park and the finest stops along the Adriatic highway.",
      "Boutique 4★ hotels, a single driver-guide, and well-paced itineraries across Croatia.",
      "The signature multi-day journey from Krka Tours.",
    ],
    destinations: ["Plitvice", "Zadar", "Krka", "Šibenik", "Split", "Dubrovnik"],
    highlights: [
      "Plitvice Lakes on the way south",
      "Zadar Sea Organ",
      "Krka National Park waterfalls",
      "Split — Diocletian's Palace",
      "Dubrovnik city walls",
    ],
    itinerary: [
      { time: "Day 1", title: "Zagreb → Plitvice → Zadar", text: "Lakes morning, coast by evening." },
      { time: "Day 2", title: "Zadar & Šibenik", text: "Sea Organ and UNESCO cathedral." },
      { time: "Day 3", title: "Krka & Split", text: "Waterfalls and palace tour." },
      { time: "Day 4", title: "Split", text: "Free day or optional island trip." },
      { time: "Day 5", title: "Split → Dubrovnik", text: "Coastal drive via Ston." },
      { time: "Day 6", title: "Dubrovnik", text: "Old town and walls." },
      { time: "Day 7", title: "Departure", text: "Airport transfer (optional)." },
    ],
    included: [...STANDARD_INCLUDED, "6 nights boutique hotels", "Daily breakfast", "Local guides"],
    notIncluded: ["Flights", "Park fees", "Lunches and dinners"],
    pricing: privatePricing(980, 830, 710),
  },
  {
    ...BASE,
    slug: "zagreb-city-break",
    title: "Zagreb City Break",
    shortTitle: "Zagreb City Break",
    duration: "3 days",
    durationDays: "3 days",
    priceFrom: 310,
    image: tourZagrebCityBreak,
    intro:
      "Three days in Croatia's capital — upper town, museums, markets, cafés and the best of continental Croatian culture.",
    description:
      "A perfect long weekend: guided city tours by day, Tkalčićeva café street by night.",
    overview: [
      "Zagreb is one of Europe's most underrated capitals — art nouveau architecture, world-class museums and a café culture to rival Vienna.",
      "Three private days with a local guide: Upper Town, museums, Mirogoj cemetery, Jarun lake and the best restaurants in town.",
      "Ideal as a standalone trip or the start of a longer Croatian adventure.",
    ],
    destinations: ["Zagreb Upper Town", "Museums quarter", "Maksimir & Jarun"],
    highlights: [
      "St. Mark's Church and Upper Town",
      "Dolac market and Tkalčićeva street",
      "Museum of Broken Relationships",
      "Mirogoj cemetery",
      "Local food and wine recommendations",
    ],
    itinerary: [
      { time: "Day 1", title: "Upper Town", text: "Cathedral, St. Mark's, Stone Gate, funicular." },
      { time: "Day 2", title: "Museums & parks", text: "Museum quarter and Maksimir park." },
      { time: "Day 3", title: "Local life", text: "Market, cafés and optional wine bar tour." },
    ],
    included: [...STANDARD_INCLUDED, "2 nights central hotel", "Daily breakfast", "Museum tickets"],
    notIncluded: ["Meals", "Flights", "Personal shopping"],
    pricing: privatePricing(420, 360, 310),
  },
  {
    ...BASE,
    slug: "croatia-wine-multiday-tour",
    title: "Croatia Wine Tour",
    shortTitle: "Wine Tour",
    badge: "Wine",
    duration: "4 days",
    durationDays: "4 days",
    priceFrom: 375,
    image: tourWine,
    intro:
      "Four days through Croatia's finest wine regions — Plešivica, Istria and Slavonia — with tastings, cellar visits and gourmet lunches.",
    description:
      "Meet winemakers, taste indigenous grapes like Graševina and Teran, and discover why Croatian wine is Europe's best-kept secret.",
    overview: [
      "A multi-day immersion in Croatian wine culture, from the sparkling wines of Plešivica to the bold Teran of Istria.",
      "Private tastings at family wineries, paired lunches and scenic drives through vineyard country.",
      "For wine lovers who want depth, not just a day trip.",
    ],
    destinations: ["Plešivica", "Istria", "Slavonia"],
    highlights: [
      "6+ winery visits across three regions",
      "20+ wine tastings",
      "Truffle lunch in Istria",
      "Meet local winemakers",
      "Wine pairing dinners",
    ],
    itinerary: [
      { time: "Day 1", title: "Plešivica", text: "Sparkling and still wines west of Zagreb." },
      { time: "Day 2", title: "Plešivica → Istria", text: "Drive to Istria, Malvasia and Teran tastings." },
      { time: "Day 3", title: "Istria", text: "Truffle lunch and hilltop winery visits." },
      { time: "Day 4", title: "Return to Zagreb", text: "Final tasting and drop-off." },
    ],
    included: [...STANDARD_INCLUDED, "3 nights accommodation", "All tastings", "Two gourmet lunches"],
    notIncluded: ["Bottle purchases", "Extra dinners", "Gratuities"],
    pricing: privatePricing(520, 440, 375),
  },
  {
    ...BASE,
    slug: "bosnia-herzegovina-multiday-tour",
    title: "Bosnia & Herzegovina Multi-Day Tour",
    shortTitle: "Bosnia & Herzegovina",
    duration: "5 days",
    durationDays: "5 days",
    priceFrom: 610,
    image: tourBosnia,
    intro:
      "Sarajevo, Mostar, Blagaj and the bridge towns of Herzegovina — five days exploring the crossroads of Ottoman and European culture.",
    description:
      "A moving journey through Bosnia's history, cuisine and stunning landscapes, with a private guide who knows every story.",
    overview: [
      "Bosnia and Herzegovina is where East meets West — mosques beside churches, Ottoman bazaars beside Austro-Hungarian boulevards.",
      "Five days from Zagreb through Sarajevo, Mostar's famous bridge, Blagaj monastery and the mountain villages of Herzegovina.",
      "A tour for curious travellers who want to understand the Balkans beyond the headlines.",
    ],
    destinations: ["Sarajevo", "Mostar", "Blagaj", "Počitelj"],
    highlights: [
      "Sarajevo Baščaršija old bazaar",
      "Mostar Old Bridge (Stari Most)",
      "Blagaj Dervish monastery",
      "Počitelj medieval town",
      "Bosnian coffee and cuisine",
    ],
    itinerary: [
      { time: "Day 1", title: "Zagreb → Sarajevo", text: "Scenic drive and old town walk." },
      { time: "Day 2", title: "Sarajevo", text: "Full day in the capital — history and culture." },
      { time: "Day 3", title: "Sarajevo → Mostar", text: "Mostar bridge and old town." },
      { time: "Day 4", title: "Mostar → Blagaj", text: "Monastery and Počitelj." },
      { time: "Day 5", title: "Return to Zagreb", text: "Drive back via scenic route." },
    ],
    included: [...STANDARD_INCLUDED, "4 nights accommodation", "Daily breakfast"],
    notIncluded: ["Meals", "Museum entries", "Border fees"],
    pricing: privatePricing(850, 720, 610),
  },
  {
    ...BASE,
    slug: "budapest-dubrovnik-tour",
    title: "Budapest to Dubrovnik Tour",
    shortTitle: "Budapest → Dubrovnik",
    duration: "10–12 days",
    durationDays: "10–12 days",
    priceFrom: 1050,
    image: tourBudapestDubrovnik,
    intro:
      "An epic overland journey from the Danube to the Adriatic — Budapest, Zagreb, Plitvice, the Dalmatian coast and Dubrovnik.",
    description:
      "Ten to twelve days across Central Europe and the Balkans, entirely by private vehicle with your own guide.",
    overview: [
      "One of our grandest itineraries: start in Budapest's thermal baths and parliament, cross Hungary and Croatia, and end on Dubrovnik's city walls.",
      "Plitvice Lakes, Split, Hvar (optional) and the entire Adriatic coast in between.",
      "For travellers who believe the journey is as important as the destination.",
    ],
    destinations: ["Budapest", "Zagreb", "Plitvice", "Split", "Dubrovnik"],
    highlights: [
      "Budapest parliament and thermal baths",
      "Zagreb city tour",
      "Plitvice Lakes National Park",
      "Split and Dalmatian islands",
      "Dubrovnik old town",
    ],
    itinerary: [
      { time: "Day 1–2", title: "Budapest", text: "Parliament, Castle District, thermal baths." },
      { time: "Day 3", title: "Budapest → Zagreb", text: "Cross into Croatia." },
      { time: "Day 4", title: "Zagreb & Plitvice", text: "City morning, lakes afternoon." },
      { time: "Day 5–6", title: "Coast to Split", text: "Zadar, Šibenik, Split." },
      { time: "Day 7–8", title: "Split & islands", text: "Palace tour, optional Hvar." },
      { time: "Day 9–10", title: "Dubrovnik", text: "Coastal drive and walled city." },
    ],
    included: [...STANDARD_INCLUDED, "9–11 nights hotels", "Daily breakfast", "All border crossings"],
    notIncluded: ["Flights", "Meals", "Park entrance fees"],
    pricing: privatePricing(1450, 1230, 1050),
  },
  {
    ...BASE,
    slug: "ljubljana-city-break",
    title: "Ljubljana City Break",
    shortTitle: "Ljubljana City Break",
    duration: "3 days",
    durationDays: "3 days",
    priceFrom: 325,
    image: tourSlovenia,
    intro:
      "Three days in Slovenia's charming capital — castle hill, riverside cafés, art nouveau streets and easy day trips to Lake Bled.",
    description:
      "Ljubljana is Europe's greenest capital. A perfect long weekend with optional Bled excursion.",
    overview: [
      "Ljubljana consistently ranks among Europe's most liveable cities — pedestrian old town, dragon bridges and a castle overlooking it all.",
      "Three private days with optional Lake Bled day trip included.",
      "Ideal standalone break or combined with a Croatia tour.",
    ],
    destinations: ["Ljubljana", "Lake Bled (optional)"],
    highlights: [
      "Ljubljana Castle and funicular",
      "Ljubljanica river embankments",
      "Prešeren Square and Triple Bridge",
      "Optional Lake Bled day trip",
      "Local wine and cuisine",
    ],
    itinerary: [
      { time: "Day 1", title: "Ljubljana Old Town", text: "Castle, river walk and market." },
      { time: "Day 2", title: "Lake Bled", text: "Day trip to Bled Castle and lakeside walk." },
      { time: "Day 3", title: "Ljubljana", text: "Museums, Tivoli park and departure." },
    ],
    included: [...STANDARD_INCLUDED, "2 nights central hotel", "Bled Castle ticket", "Daily breakfast"],
    notIncluded: ["Meals", "Flights", "Extra museum tickets"],
    pricing: privatePricing(440, 375, 325),
  },
  {
    ...BASE,
    slug: "tito-tour-balkans",
    title: "Tito Tour — Tour of the Balkans",
    shortTitle: "Tito & the Balkans",
    duration: "12–14 days",
    durationDays: "12–14 days",
    priceFrom: 1200,
    image: aboutVillage,
    intro:
      "Follow the legacy of Yugoslavia across six republics — Belgrade, Sarajevo, Zagreb, Ljubljana, Skopje and the Adriatic coast.",
    description:
      "A unique historical journey through Tito's Yugoslavia, its monuments, museums and the diverse cultures that shaped the Balkans.",
    overview: [
      "Josip Broz Tito united a diverse federation for nearly four decades. This tour traces his legacy across the lands of former Yugoslavia.",
      "From Belgrade's House of Flowers to Sarajevo's Baščaršija, Zagreb's museums and the brutalist monuments of the countryside.",
      "For history enthusiasts who want to understand the Balkans through one extraordinary life.",
    ],
    destinations: ["Belgrade", "Sarajevo", "Zagreb", "Ljubljana", "Split", "Dubrovnik"],
    highlights: [
      "Belgrade — House of Flowers mausoleum",
      "Sarajevo — war history and old bazaar",
      "Zagreb — Museum of Broken Relationships",
      "Spomenik monuments in the countryside",
      "Adriatic coast finale in Dubrovnik",
    ],
    itinerary: [
      { time: "Day 1–2", title: "Belgrade", text: "Mausoleum, fortress and old town." },
      { time: "Day 3–4", title: "Sarajevo", text: "History, bridge and bazaar." },
      { time: "Day 5–6", title: "Zagreb & Ljubljana", text: "Croatian and Slovenian capitals." },
      { time: "Day 7–9", title: "Coast", text: "Split, monuments and islands." },
      { time: "Day 10–12", title: "Dubrovnik", text: "Walled city and departure." },
    ],
    included: [...STANDARD_INCLUDED, "11–13 nights hotels", "Daily breakfast", "Museum entries"],
    notIncluded: ["Flights", "Meals", "Some monument sites"],
    pricing: privatePricing(1650, 1400, 1200),
  },
  {
    ...BASE,
    slug: "vienna-dubrovnik-tour",
    title: "Vienna to Dubrovnik Tour",
    shortTitle: "Vienna → Dubrovnik",
    duration: "10–12 days",
    durationDays: "10–12 days",
    priceFrom: 1080,
    image: tourViennaDubrovnik,
    intro:
      "From imperial Vienna through Slovenia and Croatia to Dubrovnik — ten days of Habsburg grandeur and Adriatic beauty.",
    description:
      "Start in Vienna's palaces, cross the Alps at Lake Bled, and descend to the Dalmatian coast by private vehicle.",
    overview: [
      "Vienna's Schönbrunn Palace, Ljubljana's charm, Plitvice's waterfalls and Dubrovnik's walls — ten unforgettable days.",
      "The grand Central European tour for travellers who want culture, nature and coast in one seamless private journey.",
    ],
    destinations: ["Vienna", "Ljubljana", "Bled", "Plitvice", "Split", "Dubrovnik"],
    highlights: [
      "Vienna Schönbrunn and old town",
      "Lake Bled and Ljubljana",
      "Plitvice Lakes National Park",
      "Split — Diocletian's Palace",
      "Dubrovnik city walls",
    ],
    itinerary: [
      { time: "Day 1–2", title: "Vienna", text: "Palaces, cathedral and coffee houses." },
      { time: "Day 3", title: "Vienna → Bled", text: "Alpine drive to Lake Bled." },
      { time: "Day 4", title: "Bled → Ljubljana → Zagreb", text: "Capital stops." },
      { time: "Day 5", title: "Plitvice", text: "Full day in the national park." },
      { time: "Day 6–8", title: "Coast to Split", text: "Zadar, Šibenik, Split." },
      { time: "Day 9–10", title: "Dubrovnik", text: "Walled city exploration." },
    ],
    included: [...STANDARD_INCLUDED, "9–11 nights hotels", "Daily breakfast"],
    notIncluded: ["Flights", "Vienna museum passes", "Meals"],
    pricing: privatePricing(1480, 1260, 1080),
  },
  {
    ...BASE,
    slug: "best-of-adriatic-tour",
    title: "Best of Adriatic Tour",
    shortTitle: "Best of Adriatic",
    duration: "6 days",
    durationDays: "6 days",
    priceFrom: 670,
    image: heroCoast,
    intro:
      "Six days along the northern Adriatic — Istria, Kvarner, Zadar and Šibenik — with private guide, seafood lunches and seaside hotels.",
    description:
      "The Adriatic at its most diverse: Venetian towns, Roman ruins, national parks and crystal-clear water.",
    overview: [
      "The northern Adriatic is where Roman emperors built palaces and medieval Venetians built ports.",
      "Six days from Istria through Kvarner to Zadar and Šibenik — truffle country, Lungomare promenades and the Sea Organ.",
      "Perfect for travellers who want the coast without driving all the way to Dubrovnik.",
    ],
    destinations: ["Istria", "Opatija", "Rijeka", "Zadar", "Šibenik"],
    highlights: [
      "Motovun and Rovinj in Istria",
      "Opatija Lungomare",
      "Zadar Sea Organ",
      "Šibenik UNESCO cathedral",
      "Fresh seafood throughout",
    ],
    itinerary: [
      { time: "Day 1", title: "Zagreb → Istria", text: "Motovun and hill towns." },
      { time: "Day 2", title: "Istria → Opatija", text: "Rovinj and coastal drive." },
      { time: "Day 3", title: "Opatija & Rijeka", text: "Promenade and port city." },
      { time: "Day 4", title: "Rijeka → Zadar", text: "Sea Organ and old town." },
      { time: "Day 5", title: "Zadar → Šibenik", text: "Cathedral and Krka option." },
      { time: "Day 6", title: "Return to Zagreb", text: "Scenic drive home." },
    ],
    included: [...STANDARD_INCLUDED, "5 nights seaside hotels", "Daily breakfast"],
    notIncluded: ["Meals", "Park fees", "Wine tastings"],
    pricing: privatePricing(920, 785, 670),
  },
  {
    ...BASE,
    slug: "best-of-croatia-bosnia-tour",
    title: "Best of Croatia and Bosnia and Herzegovina Tour",
    shortTitle: "Croatia & Bosnia",
    duration: "7 days",
    durationDays: "7 days",
    priceFrom: 690,
    image: tourCroatiaBosnia,
    intro:
      "Seven days combining Croatia's Adriatic coast with Bosnia's bridge towns — Plitvice, Split, Mostar and Dubrovnik.",
    description:
      "Two countries, one journey: Croatian national parks and coastline plus the cultural richness of Herzegovina.",
    overview: [
      "Combine the best of Croatia with a meaningful detour into Bosnia and Herzegovina.",
      "Plitvice Lakes, Split's palace, Mostar's iconic bridge and Dubrovnik's walls — seven days of contrast and beauty.",
      "A route that shows how closely intertwined these neighbouring countries really are.",
    ],
    destinations: ["Plitvice", "Split", "Mostar", "Blagaj", "Dubrovnik"],
    highlights: [
      "Plitvice Lakes National Park",
      "Diocletian's Palace, Split",
      "Mostar Old Bridge",
      "Blagaj monastery",
      "Dubrovnik old town",
    ],
    itinerary: [
      { time: "Day 1", title: "Zagreb → Plitvice", text: "National park visit." },
      { time: "Day 2", title: "Plitvice → Split", text: "Coastal drive to Split." },
      { time: "Day 3", title: "Split", text: "Palace tour and free time." },
      { time: "Day 4", title: "Split → Mostar", text: "Cross into Bosnia, bridge town." },
      { time: "Day 5", title: "Mostar → Dubrovnik", text: "Blagaj stop, coast drive." },
      { time: "Day 6", title: "Dubrovnik", text: "Walled city full day." },
      { time: "Day 7", title: "Departure", text: "Airport transfer optional." },
    ],
    included: [...STANDARD_INCLUDED, "6 nights accommodation", "Daily breakfast"],
    notIncluded: ["Meals", "Park & museum fees", "Flights"],
    pricing: privatePricing(950, 810, 690),
  },
  {
    ...BASE,
    slug: "best-of-balkans-tour",
    title: "Best of Croatia, Slovenia, Montenegro and Bosnia & Herzegovina Tour",
    shortTitle: "Grand Balkans",
    duration: "14 days",
    durationDays: "14 days",
    priceFrom: 1380,
    image: tourGrandBalkans,
    intro:
      "Four countries in fourteen days — the ultimate Balkan private tour from Ljubljana to Dubrovnik via Montenegro's fjord and Bosnia's bridge towns.",
    description:
      "Our most ambitious itinerary: Alpine Slovenia, Croatian coast, Montenegro's Bay of Kotor and Bosnia's heritage in one seamless journey.",
    overview: [
      "Four countries, fourteen days, one private vehicle. This is the Balkans at their most spectacular and diverse.",
      "Lake Bled, Plitvice, Dubrovnik, Kotor Bay, Mostar and Ljubljana — every highlight of the western Balkans in a single tour.",
      "For experienced travellers who want the definitive regional journey.",
    ],
    destinations: ["Slovenia", "Croatia", "Montenegro", "Bosnia & Herzegovina"],
    highlights: [
      "Lake Bled and Ljubljana",
      "Plitvice Lakes National Park",
      "Bay of Kotor, Montenegro",
      "Mostar Old Bridge",
      "Dubrovnik city walls",
    ],
    itinerary: [
      { time: "Day 1–2", title: "Slovenia", text: "Bled and Ljubljana." },
      { time: "Day 3–4", title: "Plitvice & Zagreb", text: "National park and capital." },
      { time: "Day 5–7", title: "Adriatic coast", text: "Zadar, Split, islands." },
      { time: "Day 8–9", title: "Montenegro", text: "Kotor Bay and Budva." },
      { time: "Day 10–11", title: "Bosnia", text: "Mostar and Sarajevo." },
      { time: "Day 12–14", title: "Dubrovnik", text: "Walled city and departure." },
    ],
    included: [...STANDARD_INCLUDED, "13 nights hotels", "Daily breakfast", "Border crossings"],
    notIncluded: ["Flights", "Meals", "Park entrance fees"],
    pricing: privatePricing(1890, 1600, 1380),
  },
];
